export interface Course {
  title: string;
  slug: string;
  img: string;
  description: string;
  duration: string;
  instructor: string;
}

export const coursesData: { [category: string]: Course[] } = {
    "Cse/IT": [
      {
        title: "Full Stack Web Development (MERN)",
        slug: "full-stack-web-development-mern",
        img: "/1.jpg",
        description: "Build dynamic web applications using MongoDB, Express, React, and Node.js.",
        duration: "2 Weeks",
        instructor: "John Doe",
      },
      {
        title: "Python Programming",
        slug: "python-programming",
        img: "/2.jpg",
        description: "Master Python for development, automation, data science, and AI applications.",
        duration: "8 Weeks",
        instructor: "Jane Smith",
      },
      {
        title: "Java Development (Spring Boot)",
        slug: "java-development-spring-boot",
        img: "/3.jpg",
        description: "Build enterprise applications with Java, Spring Boot, JPA, and MySQL.",
        duration: "10 Weeks",
        instructor: "Peter Jones",
      },
      {
        title: "Data Science & Machine Learning",
        slug: "data-science-machine-learning",
        img: "/4.jpg",
        description: "Work with data using Python, Pandas, NumPy, Scikit-Learn, and ML algorithms.",
        duration: "14 Weeks",
        instructor: "Emily White",
      },
      {
        title: "Artificial Intelligence & Deep Learning",
        slug: "artificial-intelligence-deep-learning",
        img: "/5.jpg",
        description: "Learn neural networks, CNNs, RNNs, TensorFlow, and real AI model development.",
        duration: "12 Weeks",
        instructor: "Alex Carter",
      },
      {
        title: "Cybersecurity & Ethical Hacking",
        slug: "cybersecurity-ethical-hacking",
        img: "/6.jpg",
        description: "Master penetration testing, network security, Kali Linux, and ethical hacking tools.",
        duration: "10 Weeks",
        instructor: "Ryan Brooks",
      },
      {
        title: "Cloud & DevOps Engineering",
        slug: "cloud-devops-engineering",
        img: "/27.jpg",
        description: "AWS, Docker, Kubernetes, Terraform, CI/CD, GitHub Actions, Linux & cloud deployment.",
        duration: "16 Weeks",
        instructor: "Sophia Lee",
      },
      {
        title: "Mobile App Development (Flutter)",
        slug: "mobile-app-development-flutter",
        img: "/28.jpg",
        description: "Design and build Android/iOS apps using Flutter & Firebase.",
        duration: "10 Weeks",
        instructor: "Kevin Adams",
      },
      {
        title: "React & Next.js Frontend Development",
        slug: "react-next-js-frontend-development",
        img: "/29.jpg",
        description: "Advanced UI/UX engineering using React, Next.js, Tailwind, and API integration.",
        duration: "6 Weeks",
        instructor: "Nina Patel",
      },
      {
        title: "Data Structures & Algorithms (DSA)",
        slug: "data-structures-algorithms-dsa",
        img: "/210.jpg",
        description: "Crack coding interviews with DSA, problem-solving, and system thinking.",
        duration: "12 Weeks",
        instructor: "Amit Verma",
      },
      {
        title: "UI/UX Design (Figma)",
        slug: "ui-ux-design-figma",
        img: "/211.jpg",
        description: "Learn Figma, prototypes, wireframes, design systems, and real-case UI designs.",
        duration: "6 Weeks",
        instructor: "Lara Collins",
      },
      {
        title: "Software Testing (Manual + Automation)",
        slug: "software-testing-manual-automation",
        img: "/212.jpg",
        description: "Test applications using Selenium, JMeter, API testing, Agile, and QA workflows.",
        duration: "8 Weeks",
        instructor: "Mark Wilson",
      },
    ],
  
    Civil: [
      {
        title: "AutoCAD 2D/3D",
        slug: "autocad-2d-3d",
        img: "/1.jpg",
        description: "Create precise 2D/3D drawings for construction and engineering projects.",
        duration: "6 Weeks",
        instructor: "Michael Brown",
      },
      {
        title: "Revit Architecture / BIM",
        slug: "revit-architecture-bim",
        img: "/2.jpg",
        description: "Learn Building Information Modeling (BIM) for designing advanced buildings.",
        duration: "8 Weeks",
        instructor: "Sarah Green",
      },
      {
        title: "STAAD Pro",
        slug: "staad-pro",
        img: "/3.jpg",
        description: "Structural analysis and design for buildings, bridges, and civil structures.",
        duration: "8 Weeks",
        instructor: "Henry Clark",
      },
      {
        title: "3ds Max for Civil Modeling",
        slug: "3ds-max-for-civil-modeling-1",
        img: "/4.jpg",
        description: "Create architectural visualizations like interiors, exteriors, and walkthroughs.",
        duration: "6 Weeks",
        instructor: "Eva Martinez",
      },{
        title: "3ds Max for Civil Modeling",
        slug: "3ds-max-for-civil-modeling-2",
        img: "/4.jpg",
        description: "Create architectural visualizations like interiors, exteriors, and walkthroughs.",
        duration: "6 Weeks",
        instructor: "Eva Martinez",
      },{
        title: "3ds Max for Civil Modeling",
        slug: "3ds-max-for-civil-modeling-3",
        img: "/4.jpg",
        description: "Create architectural visualizations like interiors, exteriors, and walkthroughs.",
        duration: "6 Weeks",
        instructor: "Eva Martinez",
      },
    ],
  
    Mechanical: [
      {
        title: "AutoCAD Mechanical",
        slug: "autocad-mechanical",
        img: "/11.jpg",
        description: "Draft and design mechanical components with advanced AutoCAD tools.",
        duration: "7 Weeks",
        instructor: "David Black",
      },
      {
        title: "SolidWorks",
        slug: "solidworks",
        img: "/12.jpg",
        description: "3D modeling, assemblies, sheet metal design, and product simulation.",
        duration: "9 Weeks",
        instructor: "Chris Taylor",
      },
      {
        title: "CATIA",
        slug: "catia",
        img: "/13.jpg",
        description: "High-end CAD/CAM design for aerospace, automotive, and industrial models.",
        duration: "10 Weeks",
        instructor: "Sophia Lopez",
      },
      {
        title: "ANSYS",
        slug: "ansys",
        img: "/14.jpg",
        description: "Finite element analysis (FEA) for testing mechanical structures and materials.",
        duration: "8 Weeks",
        instructor: "Robert Young",
      },
    ],
  
    "Ece/Electrical": [
      {
        title: "MATLAB Programming",
        slug: "matlab-programming",
        img: "/31.jpg",
        description: "Simulate and analyze engineering, mathematical, and scientific problems.",
        duration: "8 Weeks",
        instructor: "Laura Wilson",
      },
      {
        title: "Embedded Systems & IoT",
        slug: "embedded-systems-iot",
        img: "/32.jpg",
        description: "Learn microcontrollers, Arduino, IoT devices, sensors, and C programming.",
        duration: "10 Weeks",
        instructor: "Robert King",
      },
      {
        title: "VLSI Design",
        slug: "vlsi-design",
        img: "/33.jpg",
        description: "Learn chip design, Verilog, digital circuits, and semiconductor fundamentals.",
        duration: "12 Weeks",
        instructor: "Dr. Anuj Sharma",
      },
      {
        title: "PLC & SCADA Automation",
        slug: "plc-scada-automation",
        img: "/34.jpg",
        description: "Industrial automation training with PLC programming and SCADA systems.",
        duration: "8 Weeks",
        instructor: "Harsh Patel",
      },
    ],
  
    "MBA/BBA": [
      {
        title: "Digital Marketing",
        slug: "digital-marketing",
        img: "/41.jpg",
        description: "SEO, social media marketing, ads, analytics, branding, and growth strategies.",
        duration: "6 Weeks",
        instructor: "Olivia Martinez",
      },
      {
        title: "HR Management",
        slug: "hr-management",
        img: "/42.jpg",
        description: "Learn human resource planning, recruitment, payroll, and organizational behavior.",
        duration: "8 Weeks",
        instructor: "Daniel Harris",
      },
      {
        title: "Business Analytics",
        slug: "business-analytics",
        img: "/43.jpg",
        description: "Data-driven decision-making using Excel, SQL, Tableau, and dashboards.",
        duration: "10 Weeks",
        instructor: "Alicia Brown",
      },
      {
        title: "Financial Management",
        slug: "financial-management",
        img: "/44.jpg",
        description: "Master budgeting, taxation, investment strategies, and corporate finance.",
        duration: "8 Weeks",
        instructor: "James Ford",
      },
    ],
  };
